on:
    push:
    schedule:
      - cron: '5 14 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
        - uses: lee-dohm/close-matching-issues@v2
          with:
            query: 'label:fxRate'
            token: ${{ secrets.GITHUB_TOKEN }}
