
name: Forex Emailer
on: push
jobs:
  build:
    name: Get Forex rate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./get-fx-rate
        with:
          BASE_CURRENCY: "CAD"
          TARGET_CURRENCY: "INR"
