on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Fetch exchange rate action step
        uses: ./ # Uses an action in the root directory
        id: fxrate
        with:
          base-currency: "CAD"
          target-currency: "INR"
      # Use the output from the `hello` step
      - name: Get the exchange rate
        run: echo "The exchange rate is ${{ steps.fxrate.outputs.exchange-rate }}"
      - uses: maxkomarychev/oction-create-issue@v0.7.1
        id: my_step_id
        name: Add issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "1 CAD = ${{ steps.fxrate.outputs.exchange-rate }} INR"
      - name: Print outputs
        run: |
          echo ${{ steps.my_step_id.outputs.id }}
          echo ${{ steps.my_step_id.outputs.number }}
