on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Fetch exchange rate action step
        uses: ./ # Uses an action in the root directory
        id: fxrate
        with:
          base-currency: "CAD"
          target-currency: "INR"
      # Use the output from the `hello` step
      - name: Get the exchange rate
        run: echo "The exchange rate is ${{ steps.hello.outputs.exchange-rate }}"
